server:
  port: 9001
#spring配置
spring:
  #1.应用配置
  application:
    name: ims-company #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/ims?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  http:
    log-request-details: true
#3.JPA
jpa:
  database: MySQL
  show-sql: true
  open-in-view: true
jwt:
  config:
    key: LZY-ims
    ttl: 36000000
logging:
  level:
    org.springframework.web: DEBUG
    feign.client: DEBUG