apiVersion: apps/v1
kind: Deployment
metadata:
  name: ims-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ims-inventory
  template:
    metadata:
      labels:
        app: ims-inventory
    spec:
      containers:
        - name: ims-inventory
          image: ims-inventory:1.0
          ports:
            - containerPort: 9004