apiVersion: apps/v1
kind: Deployment
metadata:
  name: ims-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ims-user
  template:
    metadata:
      labels:
        app: ims-user
    spec:
      containers:
        - name: ims-user
          image: ims-user:1.0
          ports:
            - containerPort: 9002