eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    prefer-ip-address: true
    instance-id: ims-product
server:
  port: 9003
spring:
  application:
    name: ims-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ims?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
jpa:
  database: MySQL
  show-sql: true
  open-in-view: true
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
  jackson:
    enabled: true
jwt:
  config:
    key: LZY-ims
    ttl: 36000000
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework: DEBUG
    com.ims: DEBUG
    feign.client: DEBUG