server:
  port: 9005
spring:
  application:
    name: ims-supplier
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/ims?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  http:
    log-request-details: true
jpa:
  database: MySQL
  show-sql: true
  open-in-view: true
jwt:
  config:
    key: LZY-ims
    ttl: 36000000
#logging:
#  level:
#    org.springframework.web: DEBUG
#    feign.client: DEBUG