server:
  port: 9000
spring:
  application:
    name: ims-gate
  cloud:
    gateway:
      routes:
        - id: company
          uri: http://ims-company.default.svc.cluster.local:9001
          predicates:
            - Path=/api/company/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: inventory
          uri: http://ims-inventory.default.svc.cluster.local:9004
          predicates:
            - Path=/api/inventory/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: product
          uri: http://ims-product.default.svc.cluster.local:9003
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: supplier
          uri: http://ims-supplier.default.svc.cluster.local:9005
          predicates:
            - Path=/api/supplier/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: user
          uri: http://ims-user.default.svc.cluster.local:9002
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: forecast
          uri: http://ims-forecasting.default.svc.cluster.local:9006
          predicates:
            - Path=/api/forecast/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
jwt:
  config:
    key: LZY-ims
    ttl: 36000000