#注册到eureka的服务地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    perfer-ip-address : true

server:
  port: 9090
spring:
  application:
    name: ims-gate
  main:
    web-application-type: reactive
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ims?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  cloud:
    gateway:
      routes:
        - id: company
          uri: http://localhost:9001
          predicates:
            - Path=/api/company/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: inventory
          uri: http://localhost:9004
          predicates:
            - Path=/api/inventory/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: product
          uri: http://localhost:9003
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: supplier
          uri: http://localhost:9005
          predicates:
            - Path=/api/supplier/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: user
          uri: http://localhost:9002
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: forecast
          uri: http://localhost:9006
          predicates:
            - Path=/api/forecast/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
jwt:
  config:
    key: LZY-ims
    ttl: 36000000