apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ims-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: ims.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ims-vue
                port:
                  number: 8080
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: ims-gate
#                port:
#                  number: 9000